import type { Metadata } from "next";
import "./globals.scss";
import type { ReactNode } from "react";
import Header from "@/app/component/header/header";

export const metadata: Metadata = {
	title: "d10 — Digital, but smarter",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang="de">
			<body>
				<Header />
				{children}
				<div className="backgroundOverlay"></div>
			</body>
		</html>
	);
}
