import type { Metadata } from "next";
import "./globals.scss";
import {ReactNode} from "react";
import Header from "@/app/component/header/header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="de">
      <body >
      <Header/>
        {children}
      </body>
    </html>
  );
}
